<header>
    <nav class="uk-navbar-container" uk-navbar>
        <div class="uk-navbar-left">

            <ul class="uk-navbar-nav">
                <li><a href="/">Index</a></li>
                <li class="uk-active">
                    <a href="#">Roles</a>
                    <div class="uk-navbar-dropdown">
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            <li class="uk-active"><a href="#">View Roles</a></li>
                            <li><a href="#">Child 2</a></li>
                            <li><a href="#">Child 3</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="/user/">User</a></li>
            </ul>

        </div>
    </nav>
</header>