<main>
    <form class="form" action="/login/">
        <div class="container">
            <label><b>Email</b></label>
            <input class="input" type="email" placeholder="Enter Email" name="email" required>

            <label><b>Password</b></label>
            <input class="input" type="password" placeholder="Enter Password" name="psw" required>

            <label><b>Repeat Password</b></label>
            <input class="input" type="password" placeholder="Repeat Password" name="psw-repeat" required>

            <!-- <input type="checkbox" checked="checked"> Remember me -->

            <!-- <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p> -->

            <div class="clearfix">
                <button class="button m-red" type="button">Cancel</button>
                <button class="button" type="submit">Sign Up</button>
            </div>
        </div>
    </form>
</main>