<main>
    <form class="form" action="/login/" method="POST">
        <div class="container">
            <label><b>Email</b></label>
            <input class="input" type="email" placeholder="Enter Email" name="email" required>

            <label><b>Password</b></label>
            <input class="input" type="password" placeholder="Enter Password" name="password" required>

            <div class="clearfix">
                <button class="button m-red" type="button">Cancel</button>
                <button class="button" name="submit" type="submit">Sign Up</button>
            </div>
        </div>
    </form>
</main>